<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	-- TU KHOA IN
SELECT * FROM Products
SELECT * FROM Products WHERE Id IN(1002, 1003, 1005, 1025)
SELECT * FROM Products WHERE CategoryId IN(SELECT Id FROM Categories WHERE Name LIKE '%W%')
SELECT * FROM Products WHERE ProductDate IS NOT NULL

-- TIME
SELECT * FROM Products
SELECT Name, MONTH(ProductDate) FROM Products
SELECT Name, DATEPART(QUARTER, ProductDate)  FROM Products
SELECT Name, DATEPART(QUARTER, ProductDate), DATEDIFF(YEAR, ProductDate, GETDATE())  FROM Products
SELECT * FROM Products WHERE DATEDIFF(YEAR, ProductDate, GETDATE()) > = 50

SELECT TOP 10 * FROM Products
-- LAM TRANG WEB MOI, HIEN RA SAN PHAM NGAU NHIEN.
SELECT TOP 10 * FROM Products ORDER BY NEWID()

-- KET NOI BANG JOIN, CAI NAY RAT QUAN TRONG. NO QUAN TRONG HON CODE JAVA NHIEU.
-- JOIN CO 4 LOAI: INNER JOIN, LEFT OUTER JOIN, RIGHT OUTER JOIN, FULL OUTER JOIN
SELECT * FROM Products P JOIN Categories C ON C.Id = P.CategoryId
-- DAY LA KET NOI TRONG, REMOTE CONTROL 1007 KHONG THAY XUAT HIEN
SELECT C.Id, C.NameVN, P.UnitPrice FROM Products P JOIN Categories C ON C.Id = P.CategoryId
-- TA SUA LAI THANH KET NOI NGOAI, REMOTE CONTROL 1007 HIEN RA, NHUNG HIEN RA NULL
SELECT C.Id, C.NameVN, P.UnitPrice FROM Products P RIGHT JOIN Categories C ON C.Id = P.CategoryId
-- YEU CAU: TRUY VAN LOAI NAO CHUA CO SAN PHAM
SELECT * FROM Categories
SELECT * FROM Categories C LEFT JOIN Products P ON C.Id = P.CategoryId
SELECT C.* FROM Categories C LEFT JOIN Products P ON C.Id = P.CategoryId
SELECT C.* FROM Categories C LEFT JOIN Products P ON C.Id = P.CategoryId WHERE P.Id IS NULL
-- CACH KHAC: CHAY KEM HON, GIA SU BANG GHI CO 1 TRIEU RECORD THI QUA LAM CHAM CHAP LUON, RAT LA TE
-- KET QUA RA GIONG CAI TREN, RAT TRUC QUAN, NHU NHAU NHUNG CACH VIET HIEU QUA VERY VERY VERY SLOWLY !
-- KHONG PHAI LUC NAO JOIN DE LAY DU LIEU, MA TA JOIN DE LAY DIEU KIEN THOI.
SELECT * FROM Categories WHERE Id NOT IN(SELECT CategoryId FROM Products)

-- TIEP THEO: PHAN TONG HOP THONG KE, LA GIA TRI KHI TA BUSINESS KINH DOANH, 
-- CHANG QUA NO LA HOAT DONG THUONG NGAY THOI, DE LEN KE HOACH SAP TOI LAM GI LAM GI DO.
-- TONG HOP CO 2 DIEU LUU Y: 1 LA NHOM DU LIEU LAI VOI NHAU + 2 LA TONG HOP
-- TUC TINH TOAN SUM,COUNT,MIN,MAX,AVG TREN NHOM DO. TUC LA GROUP BY TRUOC, SUM,COUNT... SAU.
-- TA THAY CAC SAN PHAM DUOC NHOM LAI THEO CUNG CAC NAM, VI DU 5 DONG SAN PHAM O CUNG 1 NHOM NAM 1970 2 LAN
-- ORDER BY DICH RA NOM NA RA LA SAP XEP BOI TIEU CHI GI DAY, CON GROUP BY LA NHOM LAI THEO TIEU CHI GI DO.
SELECT * FROM Products ORDER BY YEAR(ProductDate)
SELECT Name,YEAR(ProductDate)  FROM Products ORDER BY YEAR(ProductDate)
SELECT Name, CategoryId FROM Products ORDER BY CategoryId
-- BAY GIO TA THU DEM XEM TUNG LOAI NHU VAY CO BAO NHIEU SAN PHAM BANG TU KHOA 'GROUP BY'
SELECT CategoryId, SUM(Quantity) FROM Products GROUP BY CategoryId
-- TA SE DAT CHO NO BI DANH ALIAS CHO NO DE NHIN
-- SAU DAY LA CAU LENH KIEM KE KHO HANG, HANG TON KHO.
SELECT CategoryId 'LOAI', 
	SUM(Quantity) 'SO LUONG' ,
	SUM(Quantity * UnitPrice) 'GIA TRI',
	MIN(UnitPrice) 'GIA NHO NHAT',
	MAX(UnitPrice) 'GIA LON NHAT',
	AVG(UnitPrice) 'GIA TRUNG BINH'
	FROM Products 
	GROUP BY CategoryId
-- TIEP THEO TA SE JOIN NO LAI DE LAY TEN LOAI CATEGORY NAME VN, CAU LENH SQL TA SE DUNG RAT NHIEU
-- CAU LENH SELECT SE DUNG SUOT DOI, HIBERNATE CUNG CHI DUNG DUNG 1 CAU LENH SELECT THOI
-- PHAI HIEU THAT KY CAI NAY DE NANG CAO LEN, NHOM THEO GI THI SELECT THEO DO

SELECT c.NameVN 'TEN LOAI', 
	c.Id 'MA LOAI',
	SUM(Quantity) 'SO LUONG' ,
	SUM(Quantity * UnitPrice) 'GIA TRI',
	MIN(UnitPrice) 'GIA NHO NHAT',
	MAX(UnitPrice) 'GIA LON NHAT',
	AVG(UnitPrice) 'GIA TRUNG BINH'
	FROM Products p JOIN Categories c ON c.Id = p.CategoryId 
	GROUP BY C.NameVN, C.Id

-- HAVING LA DIEU KIEN LOC NHUNG NO KHAC WHERE, WHRE LA LOC CAC BAN GHI, TUC LA LOC
-- TRUOC KHI NHOM, TRONG KHI DO HAVING LA LOC SAU KHI NHOM, SAU KHI NHOM XONG THI NO MOI LOC
-- CON TA DAT DIEU KIEN CHO TUNG BAN GHI TRONG PRODUCT THI TA LOC LA WHERE
-- TRONG VI DU TREN TA DAT RA DIEU KIEN LA CHI LOC RA NHUNG SAN PHAM NAO CO SO LUONG BAN > 300 TRO LEN
-- THI TA PHAI DUNG HAVING , KHONG THE DUNG WHRE DUOC.
SELECT c.NameVN 'TEN LOAI', 
	c.Id 'MA LOAI',
	SUM(Quantity) 'SO LUONG' ,
	SUM(Quantity * UnitPrice) 'GIA TRI',
	MIN(UnitPrice) 'GIA NHO NHAT',
	MAX(UnitPrice) 'GIA LON NHAT',
	AVG(UnitPrice) 'GIA TRUNG BINH'
	FROM Products p JOIN Categories c ON c.Id = p.CategoryId 
	GROUP BY C.NameVN, C.Id
		HAVING SUM(Quantity) > 300

-- CAU LENH SELECT LA CAU LENH TA SE PHAI DUNG NHIEU NHAT, NHAT LA TRONG HIBERNATE
-- CON INSERT UPDATE DELETE THI CHUNG TA KHONG CAN DUNG, VI BEN KIA NO LAM VIEC VOI DOI TUONG
-- NO KHONG CO TRUY VAN DATA NHU CAU LENH INSERT UPDATE DELETE

-- TIEP THEO SE LA CAU LENH STORE PROCEDURE SAU KHI AN TRUA XONG, NGU TRUA, CHIEU RA QUAN COF VIET TIEP
	
	
	
	
</body>
</html>