<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>firstJsp</title>
</head>
<body>
	SUA DOI FILE README.md TREN GITHUB
	THE LA BI LOI
	SAU DO PHAI PULL GITHUB VE MOI PUSH COMMIT TIEP DUOC
	KHONG XOA DUOC COMMIT TREN GITHUB
	BAT KY SUA DOI NAO TREN GITHUB WEB THI PHAI FETCH HOAC PULL
	NGOI CA NGAY CHI VOI CAU HOI "LAM THE NAO DE XOA COMMIT ERROR"
	DOWNLOAD GITHUB SOFTWARE VE, SAU DO TACH NHUNG PHAN COMMIT ERROR DO VAO BRAND ERROR.
	
</body>
</html>