<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>firstJsp</title>
</head>
<body>
	THOI GIAN BIEU HOM NAY 31072022:
	+18:00 AN NHE - BANH MY 15K
	+18:30 TAM
	+19:00 NGU
	+03:00 DAY LAP TRINH 1.5 TIENG LUON
	+04:30 THE DUC DI BO CHO KHOE - NHO MANG 1 CHAI NUOC UONG
	 DUNG DONG HO THEO DOI MUC TIEU DI BO.
	 TIEN THE DI THE DUC THI MUA AN BANH MY 15K LUON.
	+THE DUC VE THI TRANH THU NGU 1 GIAC CHO HOI PHUC SUC KHOE
	  TRANH THU NGU DUOC THI CU NGU, TIET KIEM SUC LUC.
	+07:00 DAY TAM RUA, VE SINH CA NHAN, CON DU BAO NHIEU THOI GIAN
	THI DI LAM THOI.
	+12:00 AN COM TRUA XONG + AN IT HOA QUA CHO CO VITAMIN,
	 TRANH THU NHAM MAT NGHI 1 CHUT, DUOC CHUT NAO
	 HAY CHUT DO, CO CON HON KHONG.
	+17:48 DI KIEM CAI BANH MY 15K AN.
	THOI BUOI KINH TE KHO KHAN,TANG THU GIAM CHI, 
	TRANH THU DAU TU 1USD LA LAI 4USD, SO GI KHONG GIAU.
	+LAP TRINH TRUOC HET LA VUI VE, SAU DO MOI THANH THOI DE SUY NGHI
	SUY NGHI THANH THOI LA KIEM TIEN TU DAU TU BUON BAN.
	+NEU CU TUAN THU NGUYEN TAC DAU TU THI CHAC CHAN 100% LAI TO.
	
</body>
</html>